#!/bin/bash

private_topology_path="/path/to/your/private.json"
public_topology_path="/path/to/your/public.json"
output_topology_path="/path/to/your/blended.json"
max_desired_peers=20
max_peer_valency=2
