#!/bin/bash

private_topology_path="/path/to/your/private.json"
public_topology_path="/path/to/your/private.json"
output_topology_path="/path/to/your/blended.json"
tmp_file="./tmp.json"
max_desired_peers=20

